# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6aad1925ba7394660c694b66a333b046bc19f2357d7ea5679e01550a718f0a307daf041cf6967985fd91fbfdc11688d66b2775911ad82a29df9375ca5c685ebc

test:
  secret_key_base: a12beeaeb5d2f5360e02d1f62cd7197e1ee84471d55c3fe27af6d50095002d5843cbb5f49dd41937c4a039a29e3dff0c17adc167c8e97f9c53ec9c881bdd4f83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
